-- Chuyển sang role ACCOUNTADMIN
USE ROLE ACCOUNTADMIN;

-- Tạo warehouse
CREATE WAREHOUSE YOUTUBE_WH WITH WAREHOUSE_SIZE = 'X-SMALL';

-- Tạo database
CREATE DATABASE YOUTUBE_DB;

-- Tạo role cho DBT
CREATE ROLE YOUTUBE_ROLE;

-- Kiểm tra quyền trên warehouse
SHOW GRANTS ON WAREHOUSE YOUTUBE_WH;

-- Gán quyền sử dụng warehouse
GRANT USAGE ON WAREHOUSE YOUTUBE_WH TO ROLE YOUTUBE_ROLE;

-- Gán role cho user
GRANT ROLE YOUTUBE_ROLE TO USER tutempgmail01;

-- Cấp toàn bộ quyền trên database
GRANT ALL ON DATABASE YOUTUBE_DB TO ROLE YOUTUBE_ROLE;

-- Chuyển sang role DBT
USE ROLE YOUTUBE_ROLE;

-- Tạo schema
CREATE SCHEMA YOUTUBE_DB.YOUTUBE_SCHEMA;

-- Tạo schema
CREATE SCHEMA YOUTUBE_DB.YOUTUBE_DEV_SCHEMA;

-- Tạo schema
CREATE SCHEMA YOUTUBE_DB.YOUTUBE_PROD_SCHEMA;